# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musicPlayer.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 386)
        MainWindow.setMinimumSize(QtCore.QSize(760, 386))
        MainWindow.setMaximumSize(QtCore.QSize(760, 386))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 10, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalSliderVolume = QtWidgets.QSlider(self.centralwidget)
        self.verticalSliderVolume.setGeometry(QtCore.QRect(20, 60, 22, 231))
        self.verticalSliderVolume.setMaximum(100)
        self.verticalSliderVolume.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderVolume.setObjectName("verticalSliderVolume")
        self.labelVolumeDisplay = QtWidgets.QLabel(self.centralwidget)
        self.labelVolumeDisplay.setGeometry(QtCore.QRect(10, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelVolumeDisplay.setFont(font)
        self.labelVolumeDisplay.setAcceptDrops(False)
        self.labelVolumeDisplay.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.labelVolumeDisplay.setText("")
        self.labelVolumeDisplay.setIndent(1)
        self.labelVolumeDisplay.setObjectName("labelVolumeDisplay")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(340, 300, 351, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonAdd = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonDelete = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        self.pushButtonDeleteAll = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonDeleteAll.setObjectName("pushButtonDeleteAll")
        self.horizontalLayout.addWidget(self.pushButtonDeleteAll)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 80, 251, 42))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonMute_Unmute = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonMute_Unmute.setStyleSheet("")
        self.pushButtonMute_Unmute.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/unmute.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButtonMute_Unmute.setIcon(icon)
        self.pushButtonMute_Unmute.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonMute_Unmute.setCheckable(False)
        self.pushButtonMute_Unmute.setAutoExclusive(False)
        self.pushButtonMute_Unmute.setAutoDefault(False)
        self.pushButtonMute_Unmute.setDefault(False)
        self.pushButtonMute_Unmute.setFlat(False)
        self.pushButtonMute_Unmute.setObjectName("pushButtonMute_Unmute")
        self.horizontalLayout_2.addWidget(self.pushButtonMute_Unmute)
        self.pushButtonRewind = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonRewind.setStyleSheet("")
        self.pushButtonRewind.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/rewind.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButtonRewind.setIcon(icon1)
        self.pushButtonRewind.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonRewind.setCheckable(False)
        self.pushButtonRewind.setAutoExclusive(False)
        self.pushButtonRewind.setAutoDefault(False)
        self.pushButtonRewind.setDefault(False)
        self.pushButtonRewind.setFlat(False)
        self.pushButtonRewind.setObjectName("pushButtonRewind")
        self.horizontalLayout_2.addWidget(self.pushButtonRewind)
        self.pushButtonPlay = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonPlay.setStyleSheet("")
        self.pushButtonPlay.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/play.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButtonPlay.setIcon(icon2)
        self.pushButtonPlay.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonPlay.setCheckable(False)
        self.pushButtonPlay.setAutoExclusive(False)
        self.pushButtonPlay.setAutoDefault(False)
        self.pushButtonPlay.setDefault(False)
        self.pushButtonPlay.setFlat(False)
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.horizontalLayout_2.addWidget(self.pushButtonPlay)
        self.pushButtonForward = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonForward.setStyleSheet("")
        self.pushButtonForward.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/forward.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButtonForward.setIcon(icon3)
        self.pushButtonForward.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonForward.setCheckable(False)
        self.pushButtonForward.setAutoExclusive(False)
        self.pushButtonForward.setAutoDefault(False)
        self.pushButtonForward.setDefault(False)
        self.pushButtonForward.setFlat(False)
        self.pushButtonForward.setObjectName("pushButtonForward")
        self.horizontalLayout_2.addWidget(self.pushButtonForward)
        self.pushButtonStop = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButtonStop.setStyleSheet("")
        self.pushButtonStop.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/stop.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButtonStop.setIcon(icon4)
        self.pushButtonStop.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonStop.setCheckable(False)
        self.pushButtonStop.setAutoExclusive(False)
        self.pushButtonStop.setAutoDefault(False)
        self.pushButtonStop.setDefault(False)
        self.pushButtonStop.setFlat(False)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.horizontalLayout_2.addWidget(self.pushButtonStop)
        self.listWidgetPlaylist = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetPlaylist.setGeometry(QtCore.QRect(340, 80, 351, 201))
        self.listWidgetPlaylist.setObjectName("listWidgetPlaylist")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 300, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.labelPlaying = QtWidgets.QLabel(self.centralwidget)
        self.labelPlaying.setGeometry(QtCore.QRect(70, 40, 651, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelPlaying.setFont(font)
        self.labelPlaying.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.labelPlaying.setObjectName("labelPlaying")
        self.labelTotalTime = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalTime.setGeometry(QtCore.QRect(140, 160, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelTotalTime.setFont(font)
        self.labelTotalTime.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.labelTotalTime.setObjectName("labelTotalTime")
        self.labelCurrentTime = QtWidgets.QLabel(self.centralwidget)
        self.labelCurrentTime.setGeometry(QtCore.QRect(130, 190, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCurrentTime.setFont(font)
        self.labelCurrentTime.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.labelCurrentTime.setObjectName("labelCurrentTime")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Melody Player"))
        self.label.setText(_translate("MainWindow", "Melody the MP3 Player"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add +"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete"))
        self.pushButtonDeleteAll.setText(_translate("MainWindow", "Delete All"))
        self.label_2.setText(_translate("MainWindow", "Volume"))
        self.labelPlaying.setText(_translate("MainWindow", "    Playing ..."))
        self.labelTotalTime.setText(_translate("MainWindow", "Total Time:  _ _:_ _"))
        self.labelCurrentTime.setText(_translate("MainWindow", "Current Time: _ _:_ _"))


import icon_rc
